import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

export const metadata: Metadata = {
  title: "Suzy Park's web",
  description: "Welcome to Suzy Park's web.",
};

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKR.variable} antialiased flex justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
